[program:pimcore-maintenance]
command=/usr/local/bin/php /var/www/html/bin/console pimcore:maintenance --async
user=www-data
autostart=true
autorestart=true
startsecs=0
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:pimcore-messenger-consume]
command=/usr/local/bin/php /var/www/html/bin/console messenger:consume pimcore_core pimcore_maintenance pimcore_image_optimize --time-limit=300
user=www-data
autostart=true
autorestart=true
startsecs=0
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:cron]
command=/usr/sbin/cron -f -L 8
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
